#!/usr/bin/with-contenv bash

echo "Démarrage d'ioBroker..."

# Vérifiez si ioBroker est déjà installé
if [ ! -d "/opt/iobroker/node_modules" ]; then
    echo "ioBroker n'est pas installé. Installation en cours..."
    
    # Installation d'ioBroker en utilisant le script fourni
    cd /tmp
    curl -sLf https://iobroker.net/install.sh > install.sh
    bash install.sh

    # Si nous sommes ici, c'est que l'installation est terminée
    echo "Installation d'ioBroker terminée."
else
    echo "ioBroker est déjà installé, démarrage du service..."
    cd /opt/iobroker
    node node_modules/iobroker.js-controller/controller.js start
fi

# Gardez le script en cours d'exécution pour empêcher le redémarrage du conteneur
while true; do
    # Vérifiez si le processus ioBroker est toujours en cours d'exécution
    if ! pgrep -f "node /opt/iobroker/node_modules/iobroker.js-controller/controller.js" > /dev/null; then
        echo "ioBroker n'est pas en cours d'exécution. Redémarrage..."
        cd /opt/iobroker
        node node_modules/iobroker.js-controller/controller.js start
    fi
    sleep 60
done 