build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-alpine:3.18
  amd64: ghcr.io/home-assistant/amd64-base-alpine:3.18
  armhf: ghcr.io/home-assistant/armhf-base-alpine:3.18
  armv7: ghcr.io/home-assistant/armv7-base-alpine:3.18
  i386: ghcr.io/home-assistant/i386-base-alpine:3.18
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ioBroker"
  org.opencontainers.image.description: "ioBroker pour Home Assistant"
  org.opencontainers.image.source: "https://github.com/edwin-anne/addon-iobroker"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
  BASHIO_VERSION: "0.15.0" 