name: "ioBroker"
description: "Plateforme de domotique ioBroker pour Home Assistant"
version: "1.0.1"
slug: "iobroker"
init: false
arch:
  - armhf
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  backup_directory: /share/iobroker_backups
schema:
  backup_directory: str
image: "ghcr.io/{build.repository}/iobroker-{build.arch}:1.0.1"
journald: false
apparmor: false
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
  - NET_BIND_SERVICE
ports:
  8081/tcp: 8081
  8082/tcp: 8082
  8083/tcp: 8083
  8084/tcp: 8084
  8085/tcp: null
  9000/udp: 9000
  8087/tcp: null
ports_description:
  8081/tcp: "Interface d'administration"
  8082/tcp: "Port ioBroker.web"
  8083/tcp: "Port pour les adaptateurs"
  8084/tcp: "Port pour les adaptateurs"
  8085/tcp: "Port pour les adaptateurs"
  9000/udp: "Port multicast/UDP"
  8087/tcp: "Port pour les adaptateurs"
ingress: true
ingress_port: 8081
panel_icon: mdi:server-network
panel_title: ioBroker
host_network: false
host_dbus: false
uart: false
usb: false
map:
  - share:rw
  - homeassistant:ro
  - addon_config:rw
webui: "http://[HOST]:[PORT:8081]" 