#!/usr/bin/with-contenv bash

# Assurez-vous que les répertoires existent
mkdir -p /opt/iobroker
mkdir -p /data/iobroker

# Définir les permissions
chown -R iobroker:iobroker /opt/iobroker
chown -R iobroker:iobroker /data/iobroker

# Exécutez le script d'initialisation
source /etc/s6-overlay/scripts/iobroker-init.sh

# Démarrez ioBroker en tant qu'utilisateur iobroker
cd /opt/iobroker
exec s6-setuidgid iobroker node node_modules/iobroker.js-controller/controller.js 