name: "ioBroker"
description: "Plateforme domotique open-source ioBroker pour Home Assistant"
version: "1.0.0"
slug: "iobroker"
init: false
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
webui: http://[HOST]:[PORT:8081]
ingress: false
ports:
  8081/tcp: 8081
  8082/tcp: 8082
  8083/tcp: 8083
  8084/tcp: 8084
  8085/tcp: 8085
  8086/tcp: 8086
  8087/tcp: 8087
  8088/tcp: 8088
  8089/tcp: 8089
  8090/tcp: 8090
  9000/tcp: 9000
  9001/tcp: 9001
ports_description:
  8081/tcp: "Interface web Admin"
  8082/tcp: "API REST"
  8083/tcp: "ioBroker.vis"
  8084/tcp: "ioBroker.vis-2"
  8085/tcp: "Port supplémentaire"
  8086/tcp: "Port supplémentaire"
  8087/tcp: "Port supplémentaire"
  8088/tcp: "Port supplémentaire"
  8089/tcp: "Port supplémentaire"
  8090/tcp: "Port supplémentaire"
  9000/tcp: "ioBroker.cloud"
  9001/tcp: "Port supplémentaire"
uart: true
usb: true
gpio: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
apparmor: false
host_network: true
full_access: true
map:
  - share:rw
  - config:rw
  - homeassistant:ro
options:
  log_level: "info"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal) 