name: "ioBroker"
description: "ioBroker Home Assistant Add-on"
version: "1.0.0"
slug: "iobroker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8081/tcp: 8081
ports_description:
  "8081/tcp": "Web interface"
map:
  - config:rw
schema: {}
options: {}
volumes:
  - /app/data:/app/data
environment:
  NODE_ENV: production 