name: "ioBroker"
version: "1.0.0"
slug: "iobroker"
description: "ioBroker Home Assistant Add-on"
url: "https://github.com/edwin-anne/addon-iobroker"
arch:
  - amd64
  - armv7
  - arm64
startup: application
boot: auto
ports:
  "8081/tcp": 8081
ports_description:
  "8081/tcp": "Web interface"
map:
  - config:rw
schema: {}
options: {}
volumes:
  - /app/data:/app/data
environment:
  NODE_ENV: production 